// Auto-generated by scripts/convert_data.py — DO NOT EDIT MANUALLY
// NASA GISTEMP v4 — Global Temperature Anomalies (°C, 1951-1980 baseline)
// Source: https://datahub.io/core/global-temp

const TEMP_DATA = [
  {
    "year": 1880,
    "mean": -0.1725
  },
  {
    "year": 1881,
    "mean": -0.0883
  },
  {
    "year": 1882,
    "mean": -0.1067
  },
  {
    "year": 1883,
    "mean": -0.1742
  },
  {
    "year": 1884,
    "mean": -0.2808
  },
  {
    "year": 1885,
    "mean": -0.3317
  },
  {
    "year": 1886,
    "mean": -0.3158
  },
  {
    "year": 1887,
    "mean": -0.3667
  },
  {
    "year": 1888,
    "mean": -0.1758
  },
  {
    "year": 1889,
    "mean": -0.1092
  },
  {
    "year": 1890,
    "mean": -0.3558
  },
  {
    "year": 1891,
    "mean": -0.2292
  },
  {
    "year": 1892,
    "mean": -0.28
  },
  {
    "year": 1893,
    "mean": -0.3192
  },
  {
    "year": 1894,
    "mean": -0.3108
  },
  {
    "year": 1895,
    "mean": -0.2392
  },
  {
    "year": 1896,
    "mean": -0.12
  },
  {
    "year": 1897,
    "mean": -0.1175
  },
  {
    "year": 1898,
    "mean": -0.2825
  },
  {
    "year": 1899,
    "mean": -0.1825
  },
  {
    "year": 1900,
    "mean": -0.0867
  },
  {
    "year": 1901,
    "mean": -0.16
  },
  {
    "year": 1902,
    "mean": -0.2858
  },
  {
    "year": 1903,
    "mean": -0.3767
  },
  {
    "year": 1904,
    "mean": -0.4775
  },
  {
    "year": 1905,
    "mean": -0.2683
  },
  {
    "year": 1906,
    "mean": -0.2292
  },
  {
    "year": 1907,
    "mean": -0.3933
  },
  {
    "year": 1908,
    "mean": -0.43
  },
  {
    "year": 1909,
    "mean": -0.4867
  },
  {
    "year": 1910,
    "mean": -0.4408
  },
  {
    "year": 1911,
    "mean": -0.45
  },
  {
    "year": 1912,
    "mean": -0.3675
  },
  {
    "year": 1913,
    "mean": -0.3492
  },
  {
    "year": 1914,
    "mean": -0.1567
  },
  {
    "year": 1915,
    "mean": -0.1433
  },
  {
    "year": 1916,
    "mean": -0.3617
  },
  {
    "year": 1917,
    "mean": -0.4617
  },
  {
    "year": 1918,
    "mean": -0.2992
  },
  {
    "year": 1919,
    "mean": -0.2783
  },
  {
    "year": 1920,
    "mean": -0.275
  },
  {
    "year": 1921,
    "mean": -0.1908
  },
  {
    "year": 1922,
    "mean": -0.2842
  },
  {
    "year": 1923,
    "mean": -0.2658
  },
  {
    "year": 1924,
    "mean": -0.2708
  },
  {
    "year": 1925,
    "mean": -0.2225
  },
  {
    "year": 1926,
    "mean": -0.1067
  },
  {
    "year": 1927,
    "mean": -0.2175
  },
  {
    "year": 1928,
    "mean": -0.2
  },
  {
    "year": 1929,
    "mean": -0.3583
  },
  {
    "year": 1930,
    "mean": -0.1575
  },
  {
    "year": 1931,
    "mean": -0.0883
  },
  {
    "year": 1932,
    "mean": -0.155
  },
  {
    "year": 1933,
    "mean": -0.2817
  },
  {
    "year": 1934,
    "mean": -0.1217
  },
  {
    "year": 1935,
    "mean": -0.1967
  },
  {
    "year": 1936,
    "mean": -0.1442
  },
  {
    "year": 1937,
    "mean": -0.0275
  },
  {
    "year": 1938,
    "mean": 0.0008
  },
  {
    "year": 1939,
    "mean": -0.0167
  },
  {
    "year": 1940,
    "mean": 0.125
  },
  {
    "year": 1941,
    "mean": 0.1867
  },
  {
    "year": 1942,
    "mean": 0.0675
  },
  {
    "year": 1943,
    "mean": 0.0892
  },
  {
    "year": 1944,
    "mean": 0.2033
  },
  {
    "year": 1945,
    "mean": 0.0925
  },
  {
    "year": 1946,
    "mean": -0.0733
  },
  {
    "year": 1947,
    "mean": -0.0275
  },
  {
    "year": 1948,
    "mean": -0.1067
  },
  {
    "year": 1949,
    "mean": -0.1092
  },
  {
    "year": 1950,
    "mean": -0.1742
  },
  {
    "year": 1951,
    "mean": -0.0683
  },
  {
    "year": 1952,
    "mean": 0.01
  },
  {
    "year": 1953,
    "mean": 0.0792
  },
  {
    "year": 1954,
    "mean": -0.1333
  },
  {
    "year": 1955,
    "mean": -0.1408
  },
  {
    "year": 1956,
    "mean": -0.1892
  },
  {
    "year": 1957,
    "mean": 0.0483
  },
  {
    "year": 1958,
    "mean": 0.0617
  },
  {
    "year": 1959,
    "mean": 0.0308
  },
  {
    "year": 1960,
    "mean": -0.025
  },
  {
    "year": 1961,
    "mean": 0.0575
  },
  {
    "year": 1962,
    "mean": 0.0308
  },
  {
    "year": 1963,
    "mean": 0.0542
  },
  {
    "year": 1964,
    "mean": -0.1992
  },
  {
    "year": 1965,
    "mean": -0.1067
  },
  {
    "year": 1966,
    "mean": -0.0575
  },
  {
    "year": 1967,
    "mean": -0.0242
  },
  {
    "year": 1968,
    "mean": -0.0842
  },
  {
    "year": 1969,
    "mean": 0.0517
  },
  {
    "year": 1970,
    "mean": 0.0258
  },
  {
    "year": 1971,
    "mean": -0.0808
  },
  {
    "year": 1972,
    "mean": 0.0083
  },
  {
    "year": 1973,
    "mean": 0.16
  },
  {
    "year": 1974,
    "mean": -0.0708
  },
  {
    "year": 1975,
    "mean": -0.0133
  },
  {
    "year": 1976,
    "mean": -0.0992
  },
  {
    "year": 1977,
    "mean": 0.1775
  },
  {
    "year": 1978,
    "mean": 0.0683
  },
  {
    "year": 1979,
    "mean": 0.1658
  },
  {
    "year": 1980,
    "mean": 0.2558
  },
  {
    "year": 1981,
    "mean": 0.3225
  },
  {
    "year": 1982,
    "mean": 0.1367
  },
  {
    "year": 1983,
    "mean": 0.3117
  },
  {
    "year": 1984,
    "mean": 0.155
  },
  {
    "year": 1985,
    "mean": 0.1158
  },
  {
    "year": 1986,
    "mean": 0.18
  },
  {
    "year": 1987,
    "mean": 0.3192
  },
  {
    "year": 1988,
    "mean": 0.3858
  },
  {
    "year": 1989,
    "mean": 0.2717
  },
  {
    "year": 1990,
    "mean": 0.445
  },
  {
    "year": 1991,
    "mean": 0.4033
  },
  {
    "year": 1992,
    "mean": 0.22
  },
  {
    "year": 1993,
    "mean": 0.23
  },
  {
    "year": 1994,
    "mean": 0.3133
  },
  {
    "year": 1995,
    "mean": 0.4442
  },
  {
    "year": 1996,
    "mean": 0.3283
  },
  {
    "year": 1997,
    "mean": 0.4633
  },
  {
    "year": 1998,
    "mean": 0.605
  },
  {
    "year": 1999,
    "mean": 0.38
  },
  {
    "year": 2000,
    "mean": 0.3917
  },
  {
    "year": 2001,
    "mean": 0.5325
  },
  {
    "year": 2002,
    "mean": 0.6267
  },
  {
    "year": 2003,
    "mean": 0.6167
  },
  {
    "year": 2004,
    "mean": 0.5325
  },
  {
    "year": 2005,
    "mean": 0.675
  },
  {
    "year": 2006,
    "mean": 0.6375
  },
  {
    "year": 2007,
    "mean": 0.6608
  },
  {
    "year": 2008,
    "mean": 0.5433
  },
  {
    "year": 2009,
    "mean": 0.655
  },
  {
    "year": 2010,
    "mean": 0.7233
  },
  {
    "year": 2011,
    "mean": 0.6058
  },
  {
    "year": 2012,
    "mean": 0.6433
  },
  {
    "year": 2013,
    "mean": 0.6733
  },
  {
    "year": 2014,
    "mean": 0.7458
  },
  {
    "year": 2015,
    "mean": 0.8975
  },
  {
    "year": 2016,
    "mean": 1.0133
  },
  {
    "year": 2017,
    "mean": 0.92
  },
  {
    "year": 2018,
    "mean": 0.8475
  },
  {
    "year": 2019,
    "mean": 0.9758
  },
  {
    "year": 2020,
    "mean": 1.0092
  },
  {
    "year": 2021,
    "mean": 0.8483
  },
  {
    "year": 2022,
    "mean": 0.8933
  },
  {
    "year": 2023,
    "mean": 1.1692
  }
];

// NOAA Mauna Loa — Atmospheric CO2 (ppm)
// Source: https://datahub.io/core/co2-ppm

const CO2_DATA = [
  {
    "year": 1959,
    "co2": 315.98
  },
  {
    "year": 1960,
    "co2": 316.91
  },
  {
    "year": 1961,
    "co2": 317.64
  },
  {
    "year": 1962,
    "co2": 318.45
  },
  {
    "year": 1963,
    "co2": 318.99
  },
  {
    "year": 1964,
    "co2": 319.62
  },
  {
    "year": 1965,
    "co2": 320.04
  },
  {
    "year": 1966,
    "co2": 321.37
  },
  {
    "year": 1967,
    "co2": 322.18
  },
  {
    "year": 1968,
    "co2": 323.05
  },
  {
    "year": 1969,
    "co2": 324.62
  },
  {
    "year": 1970,
    "co2": 325.68
  },
  {
    "year": 1971,
    "co2": 326.32
  },
  {
    "year": 1972,
    "co2": 327.46
  },
  {
    "year": 1973,
    "co2": 329.68
  },
  {
    "year": 1974,
    "co2": 330.19
  },
  {
    "year": 1975,
    "co2": 331.13
  },
  {
    "year": 1976,
    "co2": 332.03
  },
  {
    "year": 1977,
    "co2": 333.84
  },
  {
    "year": 1978,
    "co2": 335.41
  },
  {
    "year": 1979,
    "co2": 336.84
  },
  {
    "year": 1980,
    "co2": 338.76
  },
  {
    "year": 1981,
    "co2": 340.12
  },
  {
    "year": 1982,
    "co2": 341.48
  },
  {
    "year": 1983,
    "co2": 343.15
  },
  {
    "year": 1984,
    "co2": 344.87
  },
  {
    "year": 1985,
    "co2": 346.35
  },
  {
    "year": 1986,
    "co2": 347.61
  },
  {
    "year": 1987,
    "co2": 349.31
  },
  {
    "year": 1988,
    "co2": 351.69
  },
  {
    "year": 1989,
    "co2": 353.2
  },
  {
    "year": 1990,
    "co2": 354.45
  },
  {
    "year": 1991,
    "co2": 355.7
  },
  {
    "year": 1992,
    "co2": 356.54
  },
  {
    "year": 1993,
    "co2": 357.21
  },
  {
    "year": 1994,
    "co2": 358.96
  },
  {
    "year": 1995,
    "co2": 360.97
  },
  {
    "year": 1996,
    "co2": 362.74
  },
  {
    "year": 1997,
    "co2": 363.88
  },
  {
    "year": 1998,
    "co2": 366.84
  },
  {
    "year": 1999,
    "co2": 368.54
  },
  {
    "year": 2000,
    "co2": 369.71
  },
  {
    "year": 2001,
    "co2": 371.32
  },
  {
    "year": 2002,
    "co2": 373.45
  },
  {
    "year": 2003,
    "co2": 375.98
  },
  {
    "year": 2004,
    "co2": 377.7
  },
  {
    "year": 2005,
    "co2": 379.98
  },
  {
    "year": 2006,
    "co2": 382.09
  },
  {
    "year": 2007,
    "co2": 384.02
  },
  {
    "year": 2008,
    "co2": 385.83
  },
  {
    "year": 2009,
    "co2": 387.64
  },
  {
    "year": 2010,
    "co2": 390.1
  },
  {
    "year": 2011,
    "co2": 391.85
  },
  {
    "year": 2012,
    "co2": 394.06
  },
  {
    "year": 2013,
    "co2": 396.74
  },
  {
    "year": 2014,
    "co2": 398.81
  },
  {
    "year": 2015,
    "co2": 401.01
  },
  {
    "year": 2016,
    "co2": 404.41
  },
  {
    "year": 2017,
    "co2": 406.76
  },
  {
    "year": 2018,
    "co2": 408.72
  },
  {
    "year": 2019,
    "co2": 411.65
  },
  {
    "year": 2020,
    "co2": 414.21
  },
  {
    "year": 2021,
    "co2": 416.41
  },
  {
    "year": 2022,
    "co2": 418.53
  },
  {
    "year": 2023,
    "co2": 421.08
  },
  {
    "year": 2024,
    "co2": 424.61
  },
  {
    "year": 2025,
    "co2": 427.35
  }
];

// Climate Milestones — Key events for contextual display

const MILESTONES = [
  {
    "year": 1880,
    "text": "Earliest temperature records begin"
  },
  {
    "year": 1896,
    "text": "Svante Arrhenius first predicts greenhouse warming"
  },
  {
    "year": 1958,
    "text": "CO₂ measurements begin at Mauna Loa (315 ppm)"
  },
  {
    "year": 1970,
    "text": "First Earth Day celebrated"
  },
  {
    "year": 1988,
    "text": "IPCC established by the United Nations"
  },
  {
    "year": 1992,
    "text": "UN Framework Convention on Climate Change signed at Rio Earth Summit"
  },
  {
    "year": 1997,
    "text": "Kyoto Protocol adopted"
  },
  {
    "year": 2003,
    "text": "European heat wave kills over 30,000 people"
  },
  {
    "year": 2005,
    "text": "Kyoto Protocol enters into force"
  },
  {
    "year": 2012,
    "text": "Arctic sea ice hits record low"
  },
  {
    "year": 2015,
    "text": "Paris Agreement adopted — goal to limit warming to 1.5°C"
  },
  {
    "year": 2016,
    "text": "Hottest year on record at the time"
  },
  {
    "year": 2023,
    "text": "Confirmed as hottest year in recorded history"
  },
  {
    "year": 2025,
    "text": "WEF reports AI could cut 3–6 Gt CO₂/year by 2035"
  }
];
