"""
convert_data.py — Downloads and converts NASA GISTEMP and NOAA CO2 CSVs
into JavaScript constants for the Climate Time Machine.

Output: js/data.js
"""
import csv
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

TEMP_CSV = os.path.join(SCRIPT_DIR, "annual_temp.csv")
CO2_CSV = os.path.join(SCRIPT_DIR, "co2_annual.csv")
OUTPUT_JS = os.path.join(PROJECT_ROOT, "js", "data.js")

# --- Process Temperature Data (filter by GISTEMP) ---
temp_data = []
with open(TEMP_CSV, "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        if row["Source"] == "GISTEMP":
            temp_data.append({"year": int(row["Year"]), "mean": float(row["Mean"])})

# Sort by year ascending
temp_data.sort(key=lambda x: x["year"])

# --- Process CO2 Data ---
co2_data = []
with open(CO2_CSV, "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        co2_data.append({"year": int(row["Year"]), "co2": float(row["Mean"])})

co2_data.sort(key=lambda x: x["year"])

# --- Climate Milestones ---
milestones = [
    {"year": 1880, "text": "Earliest temperature records begin"},
    {"year": 1896, "text": "Svante Arrhenius first predicts greenhouse warming"},
    {"year": 1958, "text": "CO\u2082 measurements begin at Mauna Loa (315 ppm)"},
    {"year": 1970, "text": "First Earth Day celebrated"},
    {"year": 1988, "text": "IPCC established by the United Nations"},
    {"year": 1992, "text": "UN Framework Convention on Climate Change signed at Rio Earth Summit"},
    {"year": 1997, "text": "Kyoto Protocol adopted"},
    {"year": 2003, "text": "European heat wave kills over 30,000 people"},
    {"year": 2005, "text": "Kyoto Protocol enters into force"},
    {"year": 2012, "text": "Arctic sea ice hits record low"},
    {"year": 2015, "text": "Paris Agreement adopted \u2014 goal to limit warming to 1.5\u00b0C"},
    {"year": 2016, "text": "Hottest year on record at the time"},
    {"year": 2023, "text": "Confirmed as hottest year in recorded history"},
    {"year": 2025, "text": "WEF reports AI could cut 3\u20136 Gt CO\u2082/year by 2035"},
]

# --- Write to js/data.js ---
os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)

with open(OUTPUT_JS, "w") as f:
    f.write("// Auto-generated by scripts/convert_data.py — DO NOT EDIT MANUALLY\n")
    f.write("// NASA GISTEMP v4 — Global Temperature Anomalies (°C, 1951-1980 baseline)\n")
    f.write("// Source: https://datahub.io/core/global-temp\n\n")
    f.write("const TEMP_DATA = " + json.dumps(temp_data, indent=2) + ";\n\n")
    f.write("// NOAA Mauna Loa — Atmospheric CO2 (ppm)\n")
    f.write("// Source: https://datahub.io/core/co2-ppm\n\n")
    f.write("const CO2_DATA = " + json.dumps(co2_data, indent=2) + ";\n\n")
    f.write("// Climate Milestones — Key events for contextual display\n\n")
    f.write("const MILESTONES = " + json.dumps(milestones, indent=2, ensure_ascii=False) + ";\n")

print(f"✅ Generated {OUTPUT_JS}")
print(f"   TEMP_DATA: {len(temp_data)} entries ({temp_data[0]['year']}–{temp_data[-1]['year']})")
print(f"   CO2_DATA:  {len(co2_data)} entries ({co2_data[0]['year']}–{co2_data[-1]['year']})")
print(f"   MILESTONES: {len(milestones)} entries")
